name: quize_riverpod
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  dio: ^4.0.4
  equatable: ^2.0.3
  hooks_riverpod: ^1.0.3
  html_character_entities: ^1.0.0+1
  meta: ^1.7.0



  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

